#!/usr/bin/env python3
"""Locate the manuscript statements listed in ``links.json`` inside ``main.tex``.

The blueprint never stores line numbers of the paper.  Instead every entry is
found by its label at build time:

* a *numbered* entry (``"numbered": true``) is the theorem-like environment
  (``theorem``, ``definition``, ``proposition`` or ``lemma``) that contains
  ``\\label{<label>}``;
* every other entry is the text between the comment lines
  ``% blueprint-begin: <label>`` and ``% blueprint-end: <label>``.

The resulting one-based, inclusive line ranges are written to the generated
Lean module ``WeightedChainsBlueprint/PaperSources.lean`` (ignored by Git) so
that Verso can link each node to its source lines, and ``generate-redirects.py``
recomputes them to validate the built site.  Editing ``main.tex`` therefore
never requires updating the blueprint by hand, as long as the labels and
markers move with the text they describe.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

NUMBERED_ENVIRONMENTS = ("theorem", "definition", "proposition", "lemma")
ENVIRONMENT_BEGIN = re.compile(r"^\\begin[{](theorem|definition|proposition|lemma)[}]")
ENVIRONMENT_END = re.compile(r"^\\end[{](theorem|definition|proposition|lemma)[}]")
LABEL = re.compile(r"\\label[{]([^}]*)[}]")
MARKER = re.compile(r"^%\s*blueprint-(begin|end):\s*(\S+)\s*$")
GENERATED_HEADER = "-- Generated by blueprint/scripts/paper_sources.py from main.tex; do not edit."


class PaperSourceError(ValueError):
    pass


def numbered_environments(lines: list[str]) -> list[tuple[str, int, int]]:
    """Return ``(kind, beginLine, endLine)`` for every theorem-like environment."""
    result: list[tuple[str, int, int]] = []
    open_environment: tuple[str, int] | None = None
    for line_number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if (match := ENVIRONMENT_BEGIN.match(stripped)) is not None:
            if open_environment is not None:
                raise PaperSourceError(
                    f"main.tex:{line_number}: nested \\begin{{{match.group(1)}}} inside "
                    f"\\begin{{{open_environment[0]}}} opened on line {open_environment[1]}"
                )
            open_environment = (match.group(1), line_number)
        elif (match := ENVIRONMENT_END.match(stripped)) is not None:
            if open_environment is None or open_environment[0] != match.group(1):
                raise PaperSourceError(
                    f"main.tex:{line_number}: unmatched \\end{{{match.group(1)}}}"
                )
            result.append((open_environment[0], open_environment[1], line_number))
            open_environment = None
    if open_environment is not None:
        raise PaperSourceError(
            f"main.tex:{open_environment[1]}: \\begin{{{open_environment[0]}}} is never closed"
        )
    return result


def environment_labels(lines: list[str], begin: int, end: int) -> list[str]:
    labels: list[str] = []
    for line in lines[begin - 1 : end]:
        code = line.split("%", 1)[0]
        labels.extend(LABEL.findall(code))
    return labels


def markers(lines: list[str]) -> dict[str, tuple[int, int]]:
    begins: dict[str, int] = {}
    ends: dict[str, int] = {}
    for line_number, line in enumerate(lines, start=1):
        if (match := MARKER.match(line.strip())) is None:
            continue
        kind, label = match.groups()
        table = begins if kind == "begin" else ends
        if label in table:
            raise PaperSourceError(
                f"main.tex:{line_number}: duplicate blueprint-{kind} marker for {label!r} "
                f"(first on line {table[label]})"
            )
        table[label] = line_number
    if set(begins) != set(ends):
        raise PaperSourceError(
            "unpaired blueprint markers: "
            f"begin-only {sorted(set(begins) - set(ends))}, "
            f"end-only {sorted(set(ends) - set(begins))}"
        )
    spans: dict[str, tuple[int, int]] = {}
    for label, begin in begins.items():
        end = ends[label]
        start_line, end_line = begin + 1, end - 1
        while start_line <= end_line and not lines[start_line - 1].strip():
            start_line += 1
        while end_line >= start_line and not lines[end_line - 1].strip():
            end_line -= 1
        if start_line > end_line:
            raise PaperSourceError(
                f"main.tex:{begin}: blueprint markers for {label!r} enclose no text"
            )
        spans[label] = (start_line, end_line)
    return spans


def paper_spans(lines: list[str], entries: list[dict]) -> dict[str, tuple[int, int]]:
    """Map every ``links.json`` label to its inclusive line range in ``main.tex``."""
    environments = numbered_environments(lines)
    by_label: dict[str, tuple[str, int, int]] = {}
    for kind, begin, end in environments:
        for label in environment_labels(lines, begin, end):
            if label in by_label:
                raise PaperSourceError(f"\\label{{{label}}} occurs in more than one environment")
            by_label[label] = (kind, begin, end)
    marker_spans = markers(lines)

    spans: dict[str, tuple[int, int]] = {}
    for entry in entries:
        label = entry.get("label")
        if not isinstance(label, str) or not label:
            raise PaperSourceError(f"entry {entry.get('slug')!r} has no label")
        if label in spans:
            raise PaperSourceError(f"duplicate label in links.json: {label!r}")
        if entry.get("numbered") is True:
            if label not in by_label:
                raise PaperSourceError(
                    f"numbered entry {label!r} has no \\label{{{label}}} inside a "
                    "theorem-like environment of main.tex"
                )
            kind, begin, end = by_label[label]
            if entry.get("kind") != kind:
                raise PaperSourceError(
                    f"{label!r} is a {kind} in main.tex but links.json says {entry.get('kind')!r}"
                )
            spans[label] = (begin, end)
        else:
            if label not in marker_spans:
                raise PaperSourceError(
                    f"unnumbered entry {label!r} has no '% blueprint-begin: {label}' / "
                    f"'% blueprint-end: {label}' markers in main.tex"
                )
            spans[label] = marker_spans[label]

    stray = sorted(set(marker_spans) - set(spans))
    if stray:
        raise PaperSourceError(f"blueprint markers without a links.json entry: {stray}")
    return spans


def unlinked_environments(lines: list[str], entries: list[dict]) -> list[tuple[str, int]]:
    """Theorem-like environments of ``main.tex`` that no numbered entry links to."""
    linked = {entry.get("label") for entry in entries if entry.get("numbered") is True}
    result: list[tuple[str, int]] = []
    for kind, begin, end in numbered_environments(lines):
        if not linked & set(environment_labels(lines, begin, end)):
            result.append((kind, begin))
    return result


def lean_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def render_lean(spans: dict[str, tuple[int, int]]) -> str:
    rows = "".join(
        f'  ("{lean_escape(label)}", {start}, {end}),\n' for label, (start, end) in spans.items()
    )
    return (
        f"{GENERATED_HEADER}\n"
        "namespace WeightedChainsBlueprint\n\n"
        "/-- One-based, inclusive line ranges of the manuscript statements in\n"
        "`main.tex`, keyed by blueprint label.  Regenerate with\n"
        "`python3 blueprint/scripts/paper_sources.py` after editing the paper. -/\n"
        "def paperSpans : List (String × Nat × Nat) := [\n"
        f"{rows}"
        "]\n\n"
        "end WeightedChainsBlueprint\n"
    )


def load(main_tex: Path, links: Path) -> tuple[list[str], list[dict]]:
    lines = main_tex.read_text(encoding="utf-8").splitlines()
    entries = json.loads(links.read_text(encoding="utf-8")).get("entries")
    if not isinstance(entries, list) or not entries:
        raise PaperSourceError(f"{links} does not contain a nonempty entries array")
    return lines, entries


def main() -> None:
    blueprint_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    parser.add_argument("--main-tex", type=Path, default=blueprint_root.parent / "main.tex")
    parser.add_argument("--links", type=Path, default=blueprint_root / "links.json")
    parser.add_argument(
        "--out",
        type=Path,
        default=blueprint_root / "WeightedChainsBlueprint" / "PaperSources.lean",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="only verify that main.tex and links.json agree; do not write anything",
    )
    args = parser.parse_args()

    lines, entries = load(args.main_tex, args.links)
    spans = paper_spans(lines, entries)
    for kind, line_number in unlinked_environments(lines, entries):
        print(
            f"warning: {args.main_tex.name}:{line_number}: \\begin{{{kind}}} has no blueprint "
            "entry (add a \\label{wc:...} and a links.json entry to link it)",
            file=sys.stderr,
        )
    if args.check:
        print(f"located {len(spans)} paper statements in {args.main_tex}")
        return
    rendered = render_lean(spans)
    if not args.out.exists() or args.out.read_text(encoding="utf-8") != rendered:
        args.out.write_text(rendered, encoding="utf-8")
    print(f"wrote {len(spans)} paper source ranges to {args.out}")


if __name__ == "__main__":
    try:
        main()
    except PaperSourceError as error:
        sys.exit(f"paper_sources: {error}")
